### ISSUE TITLE
Is it stable for production

### ISSUE THREAD

**Issue by LeoYu007** [BillyWei001/Packable#3]
Hi, I really appreciate having such a great library, I was just wondering if it's stable enough for production. Have you used this library in any applications already released on app stores?

**Comment by BillyWei01** [comment]
The APP developed by my team has old history. They are using protobuf as the protocol, which is not convenient for migration, so they did not use this library.
I wrote this library because of my interest. There is not much feedback about this library. I am sorry that I don’t know if anyone is using this library. I only know that some people are using my other libraries. For example, someone told me that Kuaishou is using [FastKV](https://github.com/BillyWei01/FastKV).
